name: rn-secreton

services:
  consul:
    image: hashicorp/consul:1.17
    command: agent -dev -client=0.0.0.0
    ports:
      - "8585:8500"
    environment:
      CONSUL_BIND_INTERFACE: eth0
    volumes:
      - consul-data:/consul/data
    networks:
      - rn-secreton

  vault:
    image: hashicorp/vault:1.15
    cap_add:
      - IPC_LOCK
    command: vault server -dev
    ports:
      - "8282:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    volumes:
      - vault-data:/vault/file
    networks:
      - rn-secreton

volumes:
  consul-data:
  vault-data:

networks:
  rn-secreton:
    driver: bridge
